### ISSUE TITLE
Update to Laravel 5.4

### ISSUE THREAD

**Issue by drjoju** [sclaravel/menus#1]
Hi,

Can you update the composer to use in Laravel 5.4. I think changing composer to something like:

 "require": {
    "php": ">=5.6.4",
    "illuminate/config": ">=5.3",
    "illuminate/support": ">=5.3",
    "illuminate/view": ">=5.3",
    "laravelcollective/html": ">=5.3"
},

is enought. What do you think?

Best regards

**Comment by truongthaison** [comment]
Please update version 1.1
